version: "3.4"

services:
  db:
    image: mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stocks_tracker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 82:80
    environment:
      UPLOAD_LIMIT: 100M

  api:
    build:
      context: ./api
    depends_on:
      - db
    networks:
      - internal
    ports:
      - 8080:8080
    environment:
      # https://stackoverflow.com/questions/46057625/externalising-spring-boot-properties-when-deploying-to-docker
      # https://howtodoinjava.com/spring-boot2/datasource-configuration/
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev",
        "spring.datasource.url": "jdbc:mysql://db:3306/stocks_tracker",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "security.token.secret": "c7mJbWz5s1iY5JfIaOXrRxQt3oeKnfotc7mJbWz5s1iY5JfIaOXrRxQt3oeKnfotc7mJbWz5s1iY5JfIaOXrRxQt3oeKnfot",
        "logging.level.org.root": "DEBUG",
        "logging.level.org.hibernate": "ERROR",
        "server.port": 8080
      }'

  client:
    build:
      context: ./client
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./client/public:/app:rw,cached

networks:
  internal:
    external: false

volumes:
  database:
