version: "3.4"

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:?NGINX_IMAGE is not set or empty}
      - ${PHP_IMAGE:?PHP_IMAGE is not set or empty}

services:
  client:
    # in production, we may want to use a static website hosting service
    # https://facebook.github.io/create-react-app/docs/deployment
    build:
      context: ./client
      target: nginx
      # args:
      #   - REACT_APP_API_ENTRYPOINT=${REACT_APP_API_ENTRYPOINT:?REACT_APP_API_ENTRYPOINT is not set or empty}
      cache_from:
        - ${CLIENT_IMAGE:?CLIENT_IMAGE is not set or empty}
    image: ${CLIENT_IMAGE:?CLIENT_IMAGE is not set or empty}
